# Generated by Django 4.2.11 on 2024-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='empty', max_length=254, unique=True, verbose_name='Email Address'),
        ),
    ]
