# Generated by Django 4.2.11 on 2024-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('quantity', models.IntegerField()),
                ('gacctcategory_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Account Category',
                'verbose_name_plural': 'Account Categories',
                'db_table': 'accountcategory',
            },
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('accttype_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Account Detail',
                'verbose_name_plural': 'Account Details',
                'db_table': 'accountdtl',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acctcategory_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
                'db_table': 'accounttype',
            },
        ),
        migrations.CreateModel(
            name='GameAccountCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
            options={
                'verbose_name': 'Game Account Category',
                'verbose_name_plural': 'Game Account Categories',
                'db_table': 'gameacccategory',
            },
        ),
    ]
