# Generated by Django 4.2.11 on 2024-05-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_accountcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'verbose_name_plural': 'Danh mục các tài khoản của game'},
        ),
        migrations.AlterModelOptions(
            name='accountdetail',
            options={'verbose_name_plural': 'Chi tiết tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name_plural': 'Mô tả về loại tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='gameaccountcategory',
            options={'verbose_name_plural': 'Danh mục các game'},
        ),
    ]
