# Generated by Django 4.2.11 on 2024-05-14 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_accountcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcategory',
            old_name='id',
            new_name='ac_id',
        ),
        migrations.RenameField(
            model_name='accountdetail',
            old_name='id',
            new_name='ad_id',
        ),
        migrations.RenameField(
            model_name='accounttype',
            old_name='id',
            new_name='at_id',
        ),
        migrations.RenameField(
            model_name='gameaccountcategory',
            old_name='id',
            new_name='gac_id',
        ),
    ]
