# Generated by Django 4.2.11 on 2024-05-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deferror', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deferror',
            options={'verbose_name': 'DefError'},
        ),
    ]
